# Generated by Django 4.1.2 on 2022-10-29 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtdJogadores', models.IntegerField(choices=[(23, 'Option1'), (24, 'Option2'), (25, 'Option3'), (26, 'Option4')])),
            ],
        ),
        migrations.CreateModel(
            name='TipoInfracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activated', models.BooleanField(default=True)),
                ('firstAccess', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_user_image)),
                ('idUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='main.loginlevel')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitro', models.CharField(max_length=255)),
                ('duracaoPartida', models.TimeField()),
                ('timeA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaoA', to='main.selecao')),
                ('timeB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaoB', to='main.selecao')),
                ('tipoJogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoJogo', to='main.tipojogo')),
            ],
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecao', to='main.selecao')),
                ('tipoInfracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoInfracao', to='main.tipoinfracao')),
            ],
        ),
    ]
