# Generated by Django 4.1.2 on 2022-11-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='ganhador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ganhador', to='main.selecao'),
            preserve_default=False,
        ),
    ]
