# Generated by Django 4.1.1 on 2022-11-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jogo_ganhador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='qtdJogadores',
            field=models.IntegerField(choices=[(23, 'Vintetres'), (24, 'Vintequatro'), (25, 'Vintecinco'), (26, 'Vinteseis')]),
        ),
    ]
